#!/bin/sh
#
#  .o8                                                              
# "888                                                              
#  888oooo.   .oooo.o oo.ooooo.  oooo oooo    ooo ooo. .oo.  .oo.   
#  d88' `88b d88(  "8  888' `88b  `88. `88.  .8'  `888P"Y88bP"Y88b  
#  888   888 `"Y88b.   888   888   `88..]88..8'    888   888   888  
#  888   888 o.  )88b  888   888    `888'`888'     888   888   888  
#  `Y8bod8P' 8""888P'  888bod8P'     `8'  `8'     o888o o888o o888o 
#                      888                                          
#                     o888o                                         
# 

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor DP-4 -d I II III IV V
bspc monitor HDMI-0 -d VI VII VIII IX X

bspc config border_width            4
bspc config focused_border_color    '#dfb46a'
bspc config normal_border_color     '#5c7b99'
bspc config active_border_color     '#5c7b99'

bspc config window_gap              48
bspc config top_padding             32

bspc config split_ratio             0.5
bspc config borderless_monocle      true
bspc config gapless_monocle         true

bspc config focus_follows_pointer   false

xsetroot -cursor_name left_ptr &


bspc rule -a Gimp state=floating follow=on

~/.fehbg

picom --experimental-backends &

killall -q polybar
while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done

polybar -c '$HOME/.config/polybar/config.ini' top-main &
polybar -c '$HOME/.config/polybar/config.ini' top-aux &

